services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: task_flow
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
volumes:
  db_data:
